### ISSUE TITLE
Double check/edit routes after controllers confirmed

### ISSUE THREAD

**Issue by relspeedwagon** [100devs-socialnetwork/socialnetwork-main#17]
Routes are set up for the basic functionality of transitioning "todos" app to social network app, but will want to check for continuity after controllers edits.  ALSO: there is alternate code commented in, should switch to this once unique ID's have been incorporated into Posts

**Comment by Memphis1983** [comment]
Good work! Let's keep this issue open in case we have to make changes again or we could create a new issue.
